source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/misc.conf

env = XCURSOR_THEME,Qogir
env = XCURSOR_SIZE,24
